### ISSUE TITLE
KeyError: Designator

### ISSUE THREAD

**Issue by phillb** [elec-otago/neoden-yy1-kicad#1]
Traceback (most recent call last):
  File "/home/phill/neoden-yy1-kicad/venv/bin/neoden_kicad", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/phill/neoden-yy1-kicad/bin/neoden_kicad", line 32, in <module>
    output_data, output_header = convert(new_data)
  File "/home/phill/neoden-yy1-kicad/neoden_kicad/converter.py", line 47, in convert
    output_data.append([row[key] for key in output_header])
  File "/home/phill/neoden-yy1-kicad/neoden_kicad/converter.py", line 47, in <listcomp>
    output_data.append([row[key] for key in output_header])
KeyError: 'Designator'

**Comment by tmolteno** [comment]
This means that the key 'Designator' does not exist in the CSV file. Could you attach the CSV file here, and I will try and make the error message more meaningful.

**Comment by tmolteno** [comment]
The default KICAD format for CSV files is as follows:
```
Ref,Val,Package,PosX,PosY,Rot,Side
"C1","0.1","C_0402_1005Metric",-154.940000,-105.583718,180.000000,bottom
"C2","0.7p","C_0402_1005Metric",-152.416034,-106.884654,-90.000000,bottom
"L1","5.6n","L_0402_1005Metric",-153.416492,-103.303564,-90.000000,bottom
"L2","27n","L_0402_1005Metric",-152.891438,-108.366778,180.000000,bottom
"U2","BGU7005","SOT-886",-152.900082,-105.125383,-90.000000,bottom
```

We need to map
* 'Ref' -> 'Designator'
* PosX -> 'Mid X' et.c
* 'Rot' -> 'Rotation'
* 'Val' -> 'Comment'
